apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster-spot
  region: eu-north-1

nodeGroups:
  - name: ng-2
    minSize: 2
    maxSize: 3
    instancesDistribution:
      maxPrice: 0.01
      instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 00
      spotInstancePools: 2
    #ssh:
    #publicKeyPath: ~/.ssh/id_rsa.pub

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["all"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
